### ISSUE TITLE
New rules to Russian translate

### ISSUE THREAD

**Issue by LFeh** [LFeh/coding-style#8]
Hey @vbifonixor, in the last times I added new rules to this coding styling.

Can you add this changes in your amazing Russian translate?

**Comment by vbifonixor** [comment]
@LFeh copy that, gotta start working tomorrow:)

**Comment by LFeh** [comment]
Awesome!

I hope that you like it :D

**Comment by vbifonixor** [comment]
@LFeh Sure! It was easier than I thought

**Comment by LFeh** [comment]
Do you have finished already? :open_mouth: 

Extremely fast!

Thanks @vbifonixor
